import pandas as pd
import csv
import sys
from training.langFeatures import *

hypothesis = ""
file = ""


def predDT(csvFile):
    """
    A decision tree generated by the train file
    """
    datas = pd.read_csv(csvFile)
    TP = 0
    TN = 0
    with open('trainingData/classifications.csv', 'w') as resultantCSV:
        writer = csv.writer(resultantCSV)
        writer.writerow(['result'])
        for dataRecord in range(datas.shape[0]):
            if datas.iloc[dataRecord]['VowelComboDutch'] <= 0:
                # 1 means english, 0 means dutch
                if datas.iloc[dataRecord]['CommonDutch'] <= 0:
                    Lang = 0
                else:
                    Lang = 0
            else:
                if datas.iloc[dataRecord]['StopEng'] <= 0:
                    Lang = 0
                else:
                    Lang = 1
            result = 'en' if Lang == 1 else 'nl'
            print(result)
            writer.writerow([Lang])
            if Lang == datas.iloc[dataRecord]['Lang']:
                if Lang == 0:
                    TN += 1
                else:
                    TP += 1

        resultantCSV.close()


def predict():
    if len(sys.argv) <= 2:
        print('Usage:\n\tpython3 predict.py <hypothesis> <file>'.format(
            sys.argv[0]))
        exit(1)

    # hyp = "trainingData/bin_lang_validate.csv"
    hyp = sys.argv[1]
    file = sys.argv[2]

    writeToCSV(hyp, file, test=True)
    predDT(hyp)


if __name__ == '__main__':
    predict()
